### ISSUE TITLE
Don't upload your node_modules

### ISSUE THREAD

**Issue by Murky-MoMo** [Barnac1ed/SwirledAPI#1]
this is completely unnecessary, the users that want to use your repository can just clone it and use `npm install` afterwards
you only need the package jsons for that
also on your `[message.js](https://github.com/Barnac1ed/SwirledAPI/blob/main/events/guild/message.js)` i suggest adding a check to see if the variable "command" exists, and if not return
```
    const command = client.commands.get(cmd);
``` you see, if the cmd isn't an existing key(valid command name) it will return undefined
you do check if command exists but you do it after accessing it
```
      if(command.permissions.length){
``` this will lead to a `Cannot read property of undefined` error

also consider adding a check if the message was in a dm
you do access message.member, which is null outside a guild, meaning inside a dmchannel

**Comment by Barnac1ed** [comment]
Thanks for you feedback! I'm kinda new to uploading repos to GitHub as this is technically my first public repository.

**Comment by Murky-MoMo** [comment]
Ah I see, well in that case i'll check for more issues and maybe make a pr for them :) 
good luck
